## python list vs. numpy array

In [1]:
A = list(range(10))
print(type(A))
print(A)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
import numpy as np
A2 = np.array(A)
print(type(A2))
print(A2)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(A2.shape)

(10,)


In [4]:
AA = [[1,2,3], [4,5,6]]
print(len(AA))
print(len(AA[0]))

print(type(AA))
print(AA)

2
3
<class 'list'>
[[1, 2, 3], [4, 5, 6]]


In [5]:
AA2 = np.array(AA)
print(type(AA2))
print(AA2.shape)
print(AA2)

<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


# shape

In [6]:
B = np.array(range(24))

In [7]:
print(B.shape)
print(B.shape[0])
print(B)

(24,)
24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [10]:
B2 = B.reshape((-1,3))
print(B.shape)
print(B2.shape)
print(B2)

(24,)
(8, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [12]:
B3 = B.reshape((-1, 4, 3))
print(B3.shape)
print(B3)

(2, 4, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


## numpy array - 인덱스 사용법

In [17]:
data = [[67, 87, 90, 98],
[45, 45, 56, 98],
[95, 59, 96, 88],
[65, 94, 89, 98],
[45, 65, 78, 98],
[78, 76, 98, 89],
[87, 67, 65, 56],
[89, 98, 78, 78],
[100, 78, 56, 65],
[99, 89, 87, 87],
[98, 45, 56, 54],
[65, 89, 87, 78]]

In [18]:
arr = np.array(data)

In [19]:
arr

array([[ 67,  87,  90,  98],
       [ 45,  45,  56,  98],
       [ 95,  59,  96,  88],
       [ 65,  94,  89,  98],
       [ 45,  65,  78,  98],
       [ 78,  76,  98,  89],
       [ 87,  67,  65,  56],
       [ 89,  98,  78,  78],
       [100,  78,  56,  65],
       [ 99,  89,  87,  87],
       [ 98,  45,  56,  54],
       [ 65,  89,  87,  78]])

In [20]:
arr[0] # row 0

array([67, 87, 90, 98])

In [21]:
arr[0][2] # row 0, col 2

90

In [22]:
arr[0,2]

90

In [23]:
arr[:2] # from 0 till 2 - row 0, 1

array([[67, 87, 90, 98],
       [45, 45, 56, 98]])

In [24]:
arr[:2, 0]

array([67, 45])

In [25]:
arr[:2, -2:]

array([[90, 98],
       [56, 98]])

## operation on array

In [29]:
import numpy as np
A = np.array(range(20))
AA = A/20
AAA = A < 10
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
print(AA)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [28]:
print(AAA)

[ True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False]


In [30]:
sum(AAA)

10

In [32]:
AAA = A > 15
sum(AAA)/len(AAA)

0.2