In [16]:
import numpy as np  ## 백터, 행렬 데이터 전문 모듈 numpy
import pandas as pd  ## 고수준 데이터 모델 (DataFrame) 모듈 pandas
import matplotlib.pyplot as plt  ## 차트 그리기 모듈 matplotlib
df = pd.read_csv('class1.csv', encoding='utf-8')

print('칼럼이름들', list(df.columns) ) 

print(df)


칼럼이름들 ['번호', '이름', '국어', '영어', '수학', '과학']
   번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98
5   6  장호일  78  76  98  89


In [18]:
df

번호   이름  국어  영어  수학  과학
0   1   한돌  67  87  90  98
1   2   김신  45  45  56  98
2   3  이영호  95  59  96  88
3   4  박호일  65  94  89  98
4   5  조영구  45  65  78  98
5   6  장호일  78  76  98  89

In [19]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [20]:
list(df.index)

[0, 1, 2, 3, 4, 5]

In [21]:
df.values # numpy array  형태

array([[1, '한돌', 67, 87, 90, 98],
       [2, '김신', 45, 45, 56, 98],
       [3, '이영호', 95, 59, 96, 88],
       [4, '박호일', 65, 94, 89, 98],
       [5, '조영구', 45, 65, 78, 98],
       [6, '장호일', 78, 76, 98, 89]], dtype=object)

In [22]:
type(df.values)

numpy.ndarray

In [28]:
np.sum(df.values[:, 2:], axis=0)

array([395, 426, 507, 569], dtype=object)

In [30]:
np.sum(df.values[:, 2:], axis=1)

array([342, 244, 338, 346, 286, 341], dtype=object)

In [31]:
df.values[0, 2:] # 한돌의 과목별 점수

array([67, 87, 90, 98], dtype=object)

In [32]:
total = df.values[0, 2:].sum() # 한돌의 평균 점수
print('%s: %d, %.1f' % (df.values[0, 1], total, total/4))

한돌: 342, 85.5


In [33]:
np.sum(df.values[:, 2:], axis = 1)

array([342, 244, 338, 346, 286, 341], dtype=object)

In [34]:
np.sum(df.values[:, 2:], axis = 0)

array([395, 426, 507, 569], dtype=object)

In [35]:
print(list(df.index))

[0, 1, 2, 3, 4, 5]


In [36]:
df['국어']
print(type(df['국어']))
print(type(df.국어))


<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [10]:
df.국어.sum()

395

In [11]:
kuk = df[['국어']]
print(type(kuk))


<class 'pandas.core.frame.DataFrame'>


In [12]:
df[0:5]
df['국어']

0    67
1    45
2    95
3    65
4    45
5    78
Name: 국어, dtype: int64

In [15]:
print(type(df.loc[5]))
print(df.loc[5])

<class 'pandas.core.series.Series'>
번호      6
이름    장호일
국어     78
영어     76
수학     98
과학     89
Name: 5, dtype: object


In [14]:
print(type(df.iloc[5]))
print(df.iloc[5])

<class 'pandas.core.series.Series'>
번호      6
이름    장호일
국어     78
영어     76
수학     98
과학     89
Name: 5, dtype: object


### 조건으로 필터링하기

In [ ]:
df[df.국어 >= 70]

In [ ]:
df[(df.국어 >= 70) | (df.영어 >= 70)]

In [ ]:
df.query("국어 >= 70 & 영어 >= 70")

In [ ]:
df[['국어', '영어']]

In [ ]:
subjects = ['국어', '영어', '수학', '과학']

df[subjects].sum(axis=0)
print(df[subjects].sum(axis=0))
num_st = df.국어.count()
print(df[subjects].sum(axis=0) / num_st)
print(df[subjects].max(axis=0))



In [ ]:
df['총점'] = df[subjects].sum(axis=1)
df['평균']= df['총점'] / len(subjects)
df['최고점'] = df[subjects].max(axis=1)


In [ ]:
#df[['수학']]
print(type(df.수학))
print(type(df['수학']))
print(type(df[['수학']]))

In [ ]:
print('=== 성적순')
df2 = df.sort_values(['영어', '수학'], ascending=[False, False])

df2


In [ ]:
# 완전 새롭게 index reset, 정렬
df2.reset_index(inplace=True, drop=True) 
df2

In [ ]:
df2
df2.drop(['총점'], axis=1, inplace=True)
df2

In [ ]:
df2[['이름', '평균']]

In [ ]:
df2.to_csv('sorted_class1.csv', encoding='utf-8', index=False)